import type { Product } from "@/types";

/** Productos de ejemplo cuando Supabase aún no está configurado */
export const DEMO_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Torta tres leches",
    description:
      "Bizcocho esponjoso bañado en tres leches, decoración clásica.",
    price: 18990,
    unit: "unidad",
    stock: 5,
    category: "Tortas",
    mode: "pasteleria",
    image_url: null,
    highlight: "Más pedida",
    active: true,
  },
  {
    id: 2,
    name: "Cheesecake frutos rojos",
    description: "Base de galleta, crema suave y coulis de frutos del bosque.",
    price: 14990,
    unit: "unidad",
    stock: 8,
    category: "Cheesecake",
    mode: "pasteleria",
    image_url: null,
    highlight: "Nuevo",
    active: true,
  },
  {
    id: 3,
    name: "Brownie caja x6",
    description: "Brownies húmedos con chocolate belga, ideal para regalo.",
    price: 9990,
    unit: "caja x6",
    stock: 12,
    category: "Brownies",
    mode: "pasteleria",
    image_url: null,
    highlight: null,
    active: true,
  },
  {
    id: 101,
    name: "Caja Negra 20cm",
    description: "Caja cartón premium negro mate 20x20x15cm",
    price: 1990,
    unit: "c/u",
    stock: 50,
    category: "Cartón",
    mode: "shop",
    image_url: null,
    highlight: "Premium",
    active: true,
  },
  {
    id: 102,
    name: "Caja con Visor 20cm",
    description: "Caja con tapa acetato transparente 20x20x15cm",
    price: 2490,
    unit: "c/u",
    stock: 30,
    category: "Con visor",
    mode: "shop",
    image_url: null,
    highlight: "Más pedida",
    active: true,
  },
  {
    id: 103,
    name: "Pack 10 Cajas Negras",
    description: "10 cajas negro mate 20cm. Precio mayorista",
    price: 17990,
    unit: "pack x10",
    stock: 15,
    category: "Pack",
    mode: "shop",
    image_url: null,
    highlight: "Mayorista",
    active: true,
  },
];
